// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrwkOBJcZ6Eysv803gvvOMCGQwUd71dTs',
    appId: '1:844000396103:web:2b33ca52bdf4defe930262',
    messagingSenderId: '844000396103',
    projectId: 'imprenta-x-system',
    authDomain: 'imprenta-x-system.firebaseapp.com',
    databaseURL: 'https://imprenta-x-system-default-rtdb.firebaseio.com',
    storageBucket: 'imprenta-x-system.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRRi0oXqVozfJVaIHAhhMB9w9ltK7chm8',
    appId: '1:844000396103:android:4bc88c4940822550930262',
    messagingSenderId: '844000396103',
    projectId: 'imprenta-x-system',
    databaseURL: 'https://imprenta-x-system-default-rtdb.firebaseio.com',
    storageBucket: 'imprenta-x-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKRBiGOm6NE3Xeh1OGe_G8Zx-viu102Vc',
    appId: '1:844000396103:ios:7dd407a3c1380c18930262',
    messagingSenderId: '844000396103',
    projectId: 'imprenta-x-system',
    databaseURL: 'https://imprenta-x-system-default-rtdb.firebaseio.com',
    storageBucket: 'imprenta-x-system.firebasestorage.app',
    iosBundleId: 'com.example.imprentax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKRBiGOm6NE3Xeh1OGe_G8Zx-viu102Vc',
    appId: '1:844000396103:ios:7dd407a3c1380c18930262',
    messagingSenderId: '844000396103',
    projectId: 'imprenta-x-system',
    databaseURL: 'https://imprenta-x-system-default-rtdb.firebaseio.com',
    storageBucket: 'imprenta-x-system.firebasestorage.app',
    iosBundleId: 'com.example.imprentax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrwkOBJcZ6Eysv803gvvOMCGQwUd71dTs',
    appId: '1:844000396103:web:ec033d48884ae374930262',
    messagingSenderId: '844000396103',
    projectId: 'imprenta-x-system',
    authDomain: 'imprenta-x-system.firebaseapp.com',
    databaseURL: 'https://imprenta-x-system-default-rtdb.firebaseio.com',
    storageBucket: 'imprenta-x-system.firebasestorage.app',
  );

}